"""Compatibility re-export façade for UltraView floating chrome.

Class families live in sibling modules. Consumers keep importing names from
this module; type identity is the implementation class.
"""
from __future__ import annotations

import qtawesome as qta

from .author_chrome import (
    ConnectorPopover,
    DrawPopover,
    FormatChoiceFlyout,
    PointerPopover,
    SelectionToolbar,
    ShapePopover,
    StickyPopover,
    ToolFlyoutSurface,
)
from .author_tools import (
    DEFAULT_DRAW_SUBTOOL,
    DrawPreset,
    POINTER_MODE_LASER,
    POINTER_MODE_MOUSE,
    normalize_draw_subtool,
    normalize_pointer_mode,
)
from .canvas_host import (
    CanvasHost,
    _DOT_PITCH_PX,
    _DPR_CHANGE_EVENT_TYPES,
)
from .chrome_common import (
    ULTRAVIEW_MUTED,
    UV_BRAND,
    UV_BRAND_DEEP,
    UV_CANVAS,
    UV_CANVAS_DEEP,
    UV_DANGER,
    UV_DOT,
    UV_FROST,
    UV_GLOW_MIST,
    UV_GLOW_SELECTED,
    UV_GLOW_TEAL,
    UV_GRID,
    UV_INK,
    UV_LINE,
    UV_LINE_STRONG,
    UV_MUTED,
    UV_PAPER,
    UV_PRESENTATION_ICON,
    UV_SELECTED,
    UV_SELECTED_INK,
    UV_SELECTED_WASH,
    UV_WASH,
    _ElidedLabel,
    _InlineNameEditor,
    _icon_button,
    _repolish,
    _set_flag,
    _ultraview_icon_color,
)
from .chrome_islands import (
    BoardIsland,
    CardContextIsland,
    GlobalIsland,
    NavigationIsland,
    StatusIsland,
)
from .chrome_popovers import (
    BOARD_POPOVER_WIDTH,
    BOARD_ROW_HEIGHT,
    BoardPopover,
    LayoutPicker,
    _BOARD_ACTION_WIDTH,
    _BOARD_CREATE_HEIGHT,
    _BOARD_CURRENT_ROLE,
    _BOARD_LIST_BOTTOM_PAD,
    _BOARD_POPOVER_GAP,
    _BOARD_POPOVER_MARGIN,
    _BoardList,
    _BoardListDelegate,
    _HERO_LAYOUT_IDS,
    _LAYOUT_THUMB_CELL,
    _LAYOUT_THUMB_SCHEMES,
    _LAYOUT_THUMB_SIZE,
    board_popover_height,
    layout_thumbnail_icon,
)
from .floating_layout import (
    BOARD_ISLAND_MAX_WIDTH,
    DEFAULT_NAVIGATION_ISLAND_SIZE,
    GLOBAL_ISLAND_WIDTH,
    ISLAND_HEIGHT,
    RAIL_CONTENT_HEIGHT,
    RAIL_WIDTH,
    RAIL_WIDTH_COMPACT,
    STATUS_ISLAND_WIDTH,
)
from .tool_rail import (
    AUTHOR_TOOLS,
    AUTHOR_TOOL_CONNECTOR,
    AUTHOR_TOOL_DRAW,
    AUTHOR_TOOL_SELECT,
    AUTHOR_TOOL_SHAPES,
    AUTHOR_TOOL_STICKY,
    AUTHOR_TOOL_TEXT,
    OVERLAY_AUTHOR_CONNECTOR,
    OVERLAY_AUTHOR_DRAW,
    OVERLAY_AUTHOR_FORMAT,
    OVERLAY_AUTHOR_POINTER,
    OVERLAY_AUTHOR_SHAPES,
    OVERLAY_AUTHOR_STICKY,
    PANEL_BOARDS,
    PANEL_FILTER,
    PANEL_LAYOUT,
    PANEL_LIBRARY,
    PANEL_UNPLACED,
    RAIL_BADGE_INSET,
    RAIL_BADGE_MAX_HEIGHT,
    RAIL_BUTTON_SIZE,
    RAIL_BUTTON_SIZE_AUTHOR,
    RAIL_BUTTON_SIZE_AUTHOR_COMPACT,
    RAIL_BUTTON_SIZE_COMPACT,
    RAIL_DIVIDER_CLEAR,
    RAIL_DIVIDER_CLEAR_COMPACT,
    RAIL_DIVIDER_INSET,
    RAIL_GROUP_GAP,
    RAIL_GROUP_GAP_COMPACT,
    RAIL_ICON_SIZE,
    RAIL_ICON_SIZE_AUTHOR,
    RAIL_ICON_SIZE_AUTHOR_COMPACT,
    RAIL_ICON_SIZE_COMPACT,
    RAIL_MARGINS,
    RAIL_MARGINS_COMPACT,
    RAIL_RADIUS,
    RELEASE_AUTHOR_TOOLS,
    ToolRail,
    _AuthorToolButton,
    _PointerToolButton,
    _author_tool_icon,
    _prepare_rail_pass_through,
    _rail_button,
)
