"""Compatibility façade for Qt-free UltraView board state.

UltraView is a read-only snapshot Board over five source workspaces. Wave 5
moved identity into ``mf4_analyzer.ultraview_core.model``, Board/workspace
mutators into ``board_ops``, live author mutators into ``author_ops``,
presentation/filter/axis facts into ``presentation``, and schema
legalize/migration plus the Board-payload hasher into ``serialization``.
This module immediately re-exports every moved name so existing
``from mf4_analyzer.ui.ultraview_state import normalize_board_payload``
paths keep working. Do not add new implementation here. It must not import
Qt, MainWindow, ChartStack, or analysis compute modules.
"""
from __future__ import annotations

from mf4_analyzer.ultraview_core.model import (
    AXIS_KIND_FREQUENCY,
    AXIS_KIND_ORDER,
    AXIS_KIND_TIME,
    AXIS_KIND_TIME_FREQ,
    COMPARE_FILTER_ALL,
    COMPARE_FILTERS,
    DEFAULT_BOARD_NAME,
    DEFAULT_LAYOUT_ID,
    DEFAULT_PRIMARY_RATIO,
    EQUAL_LAYOUTS,
    FREE_GRID_PRESETS,
    GRID_COLUMNS,
    GRID_MAX_COLUMN_SPAN,
    GRID_MAX_ROW_SPAN,
    GRID_MIN_COLUMN_SPAN,
    GRID_MIN_ROW_SPAN,
    GRID_RESOLUTION,
    HERO_LAYOUTS,
    LAYOUT_MODE_FREE_GRID,
    LAYOUT_MODE_TEMPLATE,
    LAYOUT_SLOTS,
    LEGACY_GRID_COLUMNS,
    LEGACY_MAX_GRID_ROWS,
    MAX_AUTHOR_OBJECTS,
    MAX_AUTHOR_POINTS,
    MAX_BOARD_MEMBERSHIP,
    MAX_GRID_ROWS,
    MAX_PLACED_CARDS,
    MAX_SHAPE_TEXT,
    MAX_STICKY_TEXT,
    MAX_STROKE_POINTS,
    MAX_TEXT_TEXT,
    MAX_UI_BOARDS,
    RATIO_MAX,
    RATIO_MIN,
    RATIO_STEP,
    SAFETY_COLUMN_MAX,
    SAFETY_COLUMN_MIN,
    SAFETY_ROW_MAX,
    SAFETY_ROW_MIN,
    SECTION_AXIS_KIND,
    SECTION_LABELS_EN,
    SECTION_LABELS_ZH,
    SOURCE_SECTIONS,
    STATUS_FRESH,
    STATUS_MISSING,
    STATUS_ORPHANED,
    STATUS_STALE,
    ULTRAVIEW_PAGE_OBJECT_NAME,
    ULTRAVIEW_REF_MIME,
    AnchorTarget,
    AuthorCommon,
    AuthorMutationResult,
    AuthorObject,
    AxisConsistencyFacts,
    BoardBox,
    BoardEditEntry,
    BoardItemKey,
    BoardPlacementSnapshot,
    BoardPoint,
    CardPlacement,
    ConnectorEndpoint,
    ConnectorObject,
    FreeGridPlacement,
    FreeGridRectPlan,
    GridAnchor,
    GridBounds,
    GridRect,
    ObjectPatch,
    PreviewMeta,
    ShapeObject,
    ShapeTextStyle,
    StickyObject,
    StrokeObject,
    TextObject,
    UltraViewBoardState,
    UltraViewRef,
    UltraViewStateError,
    UltraViewWorkspaceState,
    UnknownAuthorObject,
    _author_id,
    base_frame_bounds,
    best_template_for,
    clamp_grid_rect,
    default_board,
    default_workspace,
    grid_rect_in_safety,
    is_hero_layout,
    layout_capacity,
    layout_slots,
    make_ref,
    parse_ref_payload,
    safety_grid_bounds,
)

from mf4_analyzer.ultraview_core.board_ops import (
    active_board,
    add_ref,
    all_refs,
    apply_board_placement,
    apply_free_grid_preset,
    capture_board_placement,
    clamp_ratio,
    create_board,
    delete_board,
    duplicate_board,
    empty_slots,
    first_empty_slot,
    free_grid_default_span,
    free_grid_placement_for,
    free_grid_to_template,
    mark_workspace_mutated,
    membership_set,
    move_to_unplaced,
    nudge_ratio,
    organize_free_grid,
    organized_placements,
    place_free_grid_from_unplaced,
    place_from_unplaced,
    placed_ref_set,
    placement_for,
    plan_free_grid_rects,
    rebind_ref,
    remove_ref,
    rename_board,
    reorder_board,
    replace_free_grid_ref,
    replace_slot,
    resolve_free_grid_insert_rect,
    set_active_board,
    set_free_grid_rect,
    set_free_grid_rects,
    set_layout,
    set_presentation_flags,
    set_ratio,
    set_workspace_preview_sidecar,
    set_workspace_show_card_actions,
    slot_occupant,
    swap_slots,
    template_to_free_grid,
    _append_unplaced,
    _coerce_grid_int,
    _grid_overlaps,
    _legal_grid_rect,
    _sort_placements,
    _take_membership,
    _warn,
)

from mf4_analyzer.ultraview_core.author_ops import (
    apply_author_patches,
    apply_board_edit_entry,
    author_object_to_payload,
    board_edit_entry_byte_cost,
    create_author_object,
    delete_author_objects,
    reorder_author_object,
    set_author_locked,
    update_author_object,
    _RECOGNIZED_AUTHOR_KINDS,
    _anchor_target_from_payload,
    _author_index,
    _author_mutation,
    _author_object_from_payload,
    _author_object_id,
    _author_objects_valid,
    _author_patch_candidate,
    _author_warning,
    _box_from_payload,
    _clone_author_objects,
    _endpoint_from_payload,
    _payload_equal,
    _placement_snapshot_payload,
    _point_from_payload,
    _recognized_author_object_from_payload,
    _shape_text_style_from_payload,
)

from mf4_analyzer.ultraview_core.presentation import (
    RANGE_ABS_TOL,
    RANGE_REL_TOL,
    axis_consistency_facts,
    card_matches_compare_filter,
    derive_preview_status,
    normalize_unit,
    ranges_close,
    section_search_haystack,
)

from mf4_analyzer.ultraview_core.serialization import (
    DIGEST_SCHEMA,
    ULTRAVIEW_SCHEMA,
    _BOARD_PAYLOAD_KEYS,
    _RETIRED_BOARD_PAYLOAD_KEYS,
    _board_payload,
    _canonical_json_value,
    _legacy_grid_rect,
    _normalize_author_objects,
    _reconcile_connector_targets,
    board_identity_payload,
    board_to_payload,
    normalize_board_payload,
    normalize_workspace_payload,
    presentation_digest,
    workspace_to_payload,
)
