#!/usr/bin/env python3
"""Write the native launcher's read-only visual resources.

The running application does not execute this. Windows packaging runs it
before compiling the launcher. Output is deterministic for one source tree.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mf4_analyzer.app_meta import APP_VERSION
from mf4_analyzer.startup_launch_policy import PASSTHROUGH_FLAGS
from mf4_analyzer.startup_visual_contract import (
    SPECTRUM_LAYERS,
    TIP_RECORDS,
    content_hash,
    validate_tip_records,
    visual_payload,
)


def cpp_string(text: str) -> str:
    parts = ['"']
    for char in text:
        code = ord(char)
        if char == "\\":
            parts.append("\\\\")
        elif char == '"':
            parts.append('\\"')
        elif char == "\n":
            parts.append("\\n")
        elif 32 <= code < 127:
            parts.append(char)
        elif code <= 0xFFFF:
            parts.append(f"\\u{code:04x}")
        else:
            parts.append(f"\\U{code:08x}")
    parts.append('"')
    return "".join(parts)


def render_header(payload: dict, digest: str) -> str:
    lines = [
        "#pragma once",
        "/* Generated by tools/generate_startup_launcher_resources.py. */",
        f"static const int kStartupResourceSchema = {int(payload['schema'])};",
        f"static const char kStartupContentHash[] = {cpp_string(digest)};",
        f"static const char kStartupAppVersion[] = {cpp_string(APP_VERSION)};",
        f"static const int kStartupCardWidth = {int(payload['geometry']['card_width'])};",
        f"static const int kStartupCardHeight = {int(payload['geometry']['card_height'])};",
        f"static const int kStartupFrameIntervalMs = {int(payload['motion']['frame_interval_ms'])};",
        f"static const int kStartupTipIntervalMs = {int(payload['motion']['tip_interval_ms'])};",
        f"static const int kStartupSlowAfterMs = {int(payload['motion']['slow_after_ms'])};",
        f"static const int kStartupBreathePeriodMs = {int(payload['motion']['breathe_period_ms'])};",
        f"static const int kStartupRailPeriodMs = {int(payload['motion']['rail_period_ms'])};",
        f"static const int kStartupLargeMinHeight = {int(payload['geometry']['large_scale_min_available_height'])};",
        f"static const int kStartupWorkAreaMargin = {int(payload['geometry']['work_area_margin'])};",
        f"static const int kStartupTipCount = {len(TIP_RECORDS)};",
        "static const char* kStartupTipIds[] = {",
    ]
    for tip in TIP_RECORDS:
        lines.append(f"    {cpp_string(tip.tip_id)},")
    lines.append("};")
    lines.append("static const char* kStartupTipTitles[] = {")
    for tip in TIP_RECORDS:
        lines.append(f"    {cpp_string(tip.title)},")
    lines.append("};")
    lines.append("static const char* kStartupTipBodies[] = {")
    for tip in TIP_RECORDS:
        lines.append(f"    {cpp_string(tip.body)},")
    lines.append("};")
    lines.append("static const int kStartupSpectrumRows = 16;")
    lines.append("static const int kStartupSpectrumSamples = 461;")
    lines.append("static const float kStartupSpectrumX[] = {")
    for layer in SPECTRUM_LAYERS:
        coords = ", ".join(f"{point[0]:.6f}f" for point in layer.points)
        lines.append(f"    {coords},")
    lines.append("};")
    lines.append("static const float kStartupSpectrumY[] = {")
    for layer in SPECTRUM_LAYERS:
        coords = ", ".join(f"{point[1]:.6f}f" for point in layer.points)
        lines.append(f"    {coords},")
    lines.append("};")
    lines.append("static const char* kStartupFontCandidates[] = {")
    for family in payload["palette"]["windows_font_candidates"]:
        lines.append(f"    {cpp_string(family)},")
    lines.append("    nullptr,")
    lines.append("};")
    lines.append("static const char* kStartupPassthroughFlags[] = {")
    for flag in PASSTHROUGH_FLAGS:
        lines.append(f"    {cpp_string(flag)},")
    lines.append("    nullptr,")
    lines.append("};")
    lines.append(f"static const int kStartupPassthroughFlagCount = {len(PASSTHROUGH_FLAGS)};")
    lines.append("static const char* kStartupStageIds[] = {")
    for stage in payload["stages"]:
        lines.append(f"    {cpp_string(stage['id'])},")
    lines.append("};")
    lines.append("static const char* kStartupStageLabels[] = {")
    for stage in payload["stages"]:
        lines.append(f"    {cpp_string(stage['label'])},")
    lines.append("};")
    lines.append(f"static const char kStartupSlowStatus[] = {cpp_string(payload['slow_status'])};")
    lines.append(f"static const char kStartupRightLabel[] = {cpp_string(payload['right_label'])};")
    lines.append(f"static const char kStartupCreditLeft[] = {cpp_string(payload['credit_left'])};")
    lines.append(f"static const char kStartupAppCredit[] = {cpp_string(payload['app_credit'])};")
    lines.append(f"static const char kStartupAppName[] = {cpp_string(payload['app_name'])};")
    lines.append("")
    return "\n".join(lines)


def generate(output_dir: Path) -> dict:
    records = tuple(TIP_RECORDS)
    validate_tip_records(records)
    payload = visual_payload()
    if payload["app_version"] != APP_VERSION:
        raise SystemExit("visual payload version drifted from APP_VERSION")
    digest = content_hash(payload)
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "schema": payload["schema"],
        "app_version": APP_VERSION,
        "content_hash": digest,
        "tip_count": len(records),
        "tip_ids": [tip.tip_id for tip in records],
    }
    header_path = output_dir / "startup_resources.h"
    manifest_path = output_dir / "startup_resources.json"
    header_path.write_text(render_header(payload, digest), encoding="utf-8")
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args(argv)
    manifest = generate(args.output_dir)
    print(json.dumps({"ok": True, "content_hash": manifest["content_hash"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
